version: "3.8"
services:
  
  online-shop:
    image: front-end-online-shop-image
    container_name: front-end-online-shop-container
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:3000"








